version: "3"
networks:
  network:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c ./entrypoint.sh
    volumes:
      - ./:/app
    healthcheck:
      test: nc -z localhost 8000
      interval: 10s
      timeout: 5s
      retries: 25
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - network
    restart: always
