# Generated by Django 3.2 on 2021-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='spent',
            field=models.BooleanField(default=False),
        ),
    ]
